
# Use an official Rust runtime as a parent image
FROM --platform=linux/arm64 rust:1.67

# Set the working directory in the container to /idle_rpg
WORKDIR /idle_rpg

# Copy the current directory contents into the container at /idle_rpg
COPY . /idle_rpg

# Install cargo-watch for hot reloading
RUN cargo install cargo-watch

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV RUST_LOG info 
# Run the binary program produced by `cargo watch`
CMD ["cargo", "watch", "-x", "run"]
