version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  vector:
    image: timberio/vector:0.32.1-debian
    volumes:
      - ./vector.toml:/etc/vector/vector.toml
    ports:
      - "9000:9000"
