application:
  port: 8000
  host: 0.0.0.0
database:
  #  url: "postgresql://jimmy:jimm@0.0.0.0:5432/"
  url: "postgres://marko.bilal:7geiCYdWT2Nu@ep-winter-sunset-507869.us-west-2.aws.neon.tech/"
  name: "aion-dev"
  params: "?connect_timeout=15&connection_limit=20&pool_timeout=15"
  require_ssl: false
url: "redis://redis:6379"
